[workspace]
members = [ "hosts-edit", "hoster" ]
resolver = "2"

[profile.dist]
inherits = "release"
opt-level = 3
overflow-checks = false
debug = false
strip = true
debug-assertions = false
lto = true
codegen-units = 1
