name: 'Release'

on:
  push:
    tags:
      - 'v*'
jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  build:
    uses: BrosSquad/hosts/.github/workflows/build.yml@master
  release:
    needs: [create_release, build]
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ubuntu-latest
    steps:
      - name: Download Hosts-Edit binary
        uses: actions/download-artifact@v3
        with:
          name: hosts-edit-binary-${{ matrix.os }}
      - name: Upload Release Asset
        id: upload-release-asset
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./hosts-edit.exe
          asset_name: hosts-edit-${{ steps.git_tag.outputs.tag }}-${{ matrix.os }}.exe
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        id: upload-release-asset
        if: ${{ matrix.os != 'windows-latest' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./hosts-edit
          asset_name: hosts-edit-${{ steps.git_tag.outputs.tag }}-${{ matrix.os }}
          asset_content_type: application/octet-stream
